openapi: 3.0.0
info:
  description: 
    Prof Course adalah sebuah aplikasi LMS yang digunakan untuk<br>
    meningkatkan kompetensi dari kariyawan sebuah perusahaan
  version: "1.0.0-beta"
  title: Prof Course
tags:
  - name: Auth - User
    description: Endpoint untuk authentication user
paths:
  /api/v1/login: 
    post: 
      tags:
        - Auth - User
      summary: Login user
      operationId: loginUser
      requestBody: 
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties: 
                title: 
                  type: string
                  example: "test@gmail.com"
                  pattern: "email"
                password: 
                  type: string
                  example: "1234567"
      responses:
        '200':
          description: user berhasil login
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: 
                    type: integer
                    example: 200
                  message:
                    type: string
                  data: 
                    type: object
                    properties:
                      token: 
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                      id: 
                        type: string
                      name: 
                        type: string
                      email: 
                        type: string
                      profile:
                        type: string
        '401':
          description: user tidak dikenali
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthenticated'
        '400':
          description: user tidak dikenali
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequest'
        '500':
          description: internal server error
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/InternalServerError'
  /api/v1/forgetpassword:
    post:
      tags:
        - Auth - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: test@gmail.com"
      responses:
        '200':
          description: success mengirimkan email
          content: 
            application/json:
              schema:
                type: object
                properties:
                  code: 
                    type: integer
                    example: 200
                  message: 
                    type: string
                  data: 
                    type: object
                    properties:
                      message: 
                        type: string
                        example: Berhasil mengirim email forget password
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequest'
        '500': 
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/v1/logout:
    post:
      security:
        - bearerAuth: []
      tags:
        - Auth - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: 
                token: 
                  type: string
      responses: 
        '200':
          description: Success logout user
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  code: 
                    type: integer
                    example: 200
                  message: 
                    type: string
                    example: User berhasil logout
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /api/v1/detailcourse/{courseid}:
    get:
      security:
        - bearerAuth: []
      tags: 
        - Kursus - User
      summary: Mendapatkan data detail dari salah satu kursus
      responses:
        '200':
          description: success mengirim data detail kursus
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  code:
                    type: integer
                    example: 200
                  message: 
                    type: string
                  data: 
                    type: object
                    properties:
                      id_course:
                        type: string
                      name_course: 
                        type: string
                      description: 
                        type: string
                      url_image:
                        type: string
                      moduls:
                        type: array
                        items: 
                          type: object
                          properties: 
                            name_modul: 
                              type: string
                            videos:
                              type: array
                              items: 
                                type: object
                                properties:
                                  title: 
                                    type: string
                                  url_video:
                                    type: string
                      rating_all: 
                        type: number
                        example: 4.5
                      review: 
                        type: array
                        items: 
                          type: object
                          properties:
                            name_user: 
                              type: string 
                              example: Sujadi
                            url_image: 
                              type: string
                            body:
                              type: string
                            rating: 
                              type: number
                              example: 4.5
                      user_taken_course: 
                        type: integer
                        example: 20
                      rangking: 
                        type: array
                        items:
                          type: object
                          properties: 
                            id_user: 
                              type: string
                            name_user: 
                              type: string
                            skor:
                              type: number
        '401':
          description: user tidak dikenali
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthenticated'
        '500':
          description: Internal server error    
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/v1/courses:
    get: 
      security:
        - bearerAuth: []
      tags: 
        - Kursus - User 
      summary: Mengambil data kursus sesuai keperluan
      parameters:
        - name: sort
          in: query
          schema:
            type: string
          description: nilai pada sort adalah asc/dsc by created_at
        - name: s
          in: query
          schema: 
            type: string
          description: query untuk search kursus
        - name: limit
          in: query
          description: batas jumlah dari konten items
          schema:
            type: integer
        - name: offset
          in: query
          description: Menentukan nilai halaman konten yang akan ditampilkan
          schema:
            type: integer
      responses:
        '200': 
          description: Berhasil mengambil data course terbaru
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: 
                    type: integer
                    example: 200
                  message:
                    type: string
                  data: 
                    type: array
                    items: 
                      type: object
                      properties:
                        title:
                          type: string
                        url_image: 
                          type: string
                        id_course: 
                          type: string
        '401':
          description: User tidak dikenali
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthenticated'
        '415':
          description: nilai parameters tidak sesuai
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedMediaType'
        '500':
          description: Internal server error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/v1/specialization:
    get:
      security:
        - bearerAuth: []
      tags: 
        - Kursus - User 
      summary: Mengambil data spesialisasi sesuai keperluan
      parameters:
        - name: sort
          in: query
          schema:
            type: string
          description: nilai pada sort adalah asc/dsc by created_at
        - name: s
          in: query
          schema: 
            type: string
          description: query untuk search spesialisasi
        - name: limit
          in: query
          description: batas jumlah dari konten items
          schema:
            type: integer
        - name: offset
          in: query
          description: Menentukan nilai halaman konten yang akan ditampilkan
          schema:
            type: integer
      responses:
        '200': 
          description: Berhasil mengambil data spesialisasi terbaru
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: 
                    type: integer
                    example: 200
                  message:
                    type: string
                  data: 
                    type: array
                    items: 
                      type: object
                      properties:
                        title:
                          type: string
                        url_image: 
                          type: string
                        id_course: 
                          type: string
        '401':
          description: User tidak dikenali
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthenticated'
        '415':
          description: nilai parameters tidak sesuai
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedMediaType'
        '500':
          description: Internal server error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/v1/user/{userid}:
    get:
      tags: 
        - User - User 
      summary: mengambil data kursus dari halaman kursus saya
      security:
        - bearerAuth: []
      responses:
        '200':
          description: success mengambil data
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:



components: 
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT 
  schemas:
    InternalServerError:
      type: object
      properties:
        code: 
          type: integer
          example: 500
        message:
          type: string
          example: Internal server error
    Unauthenticated:
      type: object
      properties:
        code:
          type: integer
          example: 401
        message: 
          type: string
          example: Unauthenticated
    InvalidRequest:
      type: object
      properties:
        code: 
          type: integer
          example: 400
        message:
          type: string
          example: Invalid request
    UnsupportedMediaType:
      type: object
      properties:
        code: 
          type: integer
          example: 415
        message:
          type: string
          example: Jenis Media tidak didukung tidak sesuai



