// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: ctx, to, subject, message
func (_m *Repository) SendEmail(ctx context.Context, to string, subject string, message string) error {
	ret := _m.Called(ctx, to, subject, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, to, subject, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
