// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	locals "profcourse/business/uploads"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// UploadImage provides a mock function with given fields: ctx, header, destination
func (_m *Repository) UploadImage(ctx context.Context, header *multipart.FileHeader, destination string) (locals.Domain, error) {
	ret := _m.Called(ctx, header, destination)

	var r0 locals.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader, string) locals.Domain); ok {
		r0 = rf(ctx, header, destination)
	} else {
		r0 = ret.Get(0).(locals.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader, string) error); ok {
		r1 = rf(ctx, header, destination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
