// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	users "profcourse/business/users"

	mock "github.com/stretchr/testify/mock"
)

// PDF is an autogenerated mock type for the PDF type
type PDF struct {
	mock.Mock
}

// GeneratePDFDataReport provides a mock function with given fields: user, course
func (_m *PDF) GeneratePDFDataReport(user users.Domain, course []users.Course) (string, error) {
	ret := _m.Called(user, course)

	var r0 string
	if rf, ok := ret.Get(0).(func(users.Domain, []users.Course) string); ok {
		r0 = rf(user, course)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(users.Domain, []users.Course) error); ok {
		r1 = rf(user, course)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
