name: CI CD
on:
  push:
    branches:
      - development
      - createCICD
  pull_request:
    branches:
      - development

jobs:
  unit-test:
    name: do unit test to project go
    runs-on: ubuntu-20.04
    steps:
      - name: setup github action(CI)
        uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
      - name: running unit test
        run: go test ./... -cover
  build-push-docker:
    name: "Build image and push register"
    runs-on: ubuntu-20.04
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: create config
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          touch config.json
          echo "$CONFIG" > config.json
          chmod 777 config.json
      - name: build docker
        run: docker build -t wahyunf354/prof_course:dev .
      - name: login registry docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: push docker hub
        run: docker push wahyunf354/prof_course:dev
  deployment-ec2:
    name: "Deploy to ec2 from registry docker hub"
    runs-on: ubuntu-20.04
    needs: build-push-docker
    steps:
      - uses: actions/checkout@v2
      - name: configuration SSH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/secret.pem
          chmod 400 ~/.ssh/secret.pem
          cat >>~/.ssh/config <<END
          Host development
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/secret.pem
            StrictHostKeyChecking=no
          END
      - name: Connect EC2 & Remove All Container & Pull from Registry & Start
        run: ssh development 'docker rm -f prof_course || true && docker pull wahyunf354/prof_course:dev && docker run -d -p 9090:9090 --name=prof_course wahyunf354/prof_course:dev'