name: CI CD
on: [push, pull_request]

jobs:
  unit-test:
    name: do unit test to project go
    runs-on: ubuntu-20.04
    steps:
      - name: setup github action(CI)
        uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
      - name: running unit test
        run: go test ./... -cover

